[[redirects]]
  from = "/cookiebot/*"
  to = "https://consent.cookiebot.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cookiebotcdn/*"
  to = "https://consentcdn.cookiebot.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cookiebotcdneu/*"
  to = "https://consentcdn.cookiebot.eu/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' 'unsafe-inline' 'inline-speculation-rules' https://partytown-fuse.netlify.app https://www.googletagmanager.com; object-src 'none'; base-uri 'self';"